---
abstract: 'Giraffi API Access Module'
author:
  - 'Akira Horimoto <emperor@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Giraffi-API
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::XSAccessor: 1.13
  Crypt::SSLeay: 0.58
  JSON::Any: 1.29
  LWP::Protocol::https: 6.03
  Module::Pluggable: 4.0
  Time::Piece: 1.20_01
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/holly/perl-WWW-Giraffi-API.git
version: 0.2_03
